### ISSUE TITLE
FEATURE: Autoversion the download URL

### ISSUE THREAD

**Issue by cswendrowski** [League-of-Foundry-Developers/FoundryVTT-Module-Template#1]
Currently, the CI/CD will automatically load the version from the manifest.json for creating the release and zip files, but users often forget to update the download URL, causing releases to break.

The Github Actions workflow should be updated to automatically update that URL to prevent this issue

**Comment by spacemandev-git** [comment]
If you auto version the manifest URL it will never update through foundry. The manifest needs to point to /latest/download for it to fetch the latest version for auto updates

**Comment by cswendrowski** [comment]
Resolved as of #3
